config/routes.rb
Rails.application.routes.draw do

  get  'index' =>'contact_mailers#index'
  post 'confirm' => 'contact_mailers#confirm'
  post 'done' => 'contact_mailers#done'
  resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy]

  namespace :customer do
    get 'customers/edit'
    get 'customers/favorites'
  end

  root 'customers/items#index'
  devise_for :admins, path: 'auth', path_names: { sign_in: 'panda_and_coffee_with_ryoko_play_login', sign_out: 'panda_and_coffee_with_ryoko_play_logout', password: 'panda_and_coffee_with_ryoko_play_secret', confirmation: 'panda_and_coffee_with_ryoko_play_verification', unlock: 'panda_and_coffee_with_ryoko_play_unblock', registration: 'panda_and_coffee_with_ryoko_play_register', sign_up: 'panda_and_coffee_with_ryoko_play_cmon_let_me_in' }, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations',
  }

  namespace :admin do
    resources :categories, only: [:create, :update]
    put 'categories/:id/hide' => 'categories#hide', as: 'categories_hide'
    resources :labels, only: [:create, :update]
    put 'labels/:id/hide' => 'labels#hide', as: 'labels_hide'
    resources :artists, only: [:create, :update]
    put 'artists/:id/hide' => 'artists#hide', as: 'artists_hide'

    get 'homes/index' => 'homes#index'
    get "search" => "arrival_items#search"
    get "history_search" => "arrival_items#history_search"
    get "fav" => "items#fav"

   put "/items/:id" => "items#hide"
   resources :items, only: [:new, :create, :edit, :update, :index, :show]
   resources :arrival_items, only: [:index, :new, :create, :update]


    put "/customers/:id" => "customers#hide"
    resources :customers, only: [:index, :show, :update, :edit]
    resources :orders, only: [:index, :update]

  end

  namespace :customers do
    get 'homes/about' => "homes#about"
    get 'homes/thanks' => "homes#thanks"
    get 'homes/top' => "homes#top"
    get ':id/unsubscribe' => "homes#unsubscribe", as: "unsubscribe"
    get "customers/:id/carts" => "customers#carts"
    get "search" => "items#search"
    get "category/:id" => "items#category"
    get "orders/new2" => "orders#new_address"
    resources :rooms, only: [:show, :create]

    resource :orders, only: [:new, :create] do
      post :pay, on: :member
    end

    resources :customers, only: [:edit] do
      resources :carts, only: [:show, :create, :update, :destroy]
    end

    resources :customers, only: [:edit,:update]
    put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
    get "/customers/:id" => "customers#favorites", as: 'favorites'
    get "/items/index2" => "items#index2"

    resources :items, only: [:show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :carts, only: [:show, :create, :update, :destroy]
      resources :post_comments, only: [:create, :destroy, :edit, :update]
    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def show
  	@customer = Customer.find(params[:id])
  	@customers =Customer.page(params[:page]).per(2)
  	@orders = Order.where(customer_id: @customer.id)
  	 #総売上
  	  total = 0
      customer_total = 0
      @orders.each do |x|
        total += x.total_price
        @customer_total = x.total_price
      end
      @total = total
  end


  def hide
  	@customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
  	redirect_to root_path
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def index
    @customer =Customer.page(params[:page]).per(1)
     @orders = Order.all
     if params[:vort] == "2"
      @customers = Customer.all
    else
      @customers = Customer.all.order(created_at: :desc)
  end
end

  def update
  	@customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end
private
def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:phone_number,:email, addresses_attributes:[:id,:postal_code,:address,:is_deleted])
end
def correct_user
    user = Customer.find(params[:id])
    if current_user != customer
      redirect_to admin_customers_path(current_user)
    end
   end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    if params[:sort] == "1"
      @orders = Order.where(status: "受付").page(params[:page]).per(5).order(created_at: :desc)
    elsif params[:sort] == "2"
      @orders = Order.where(status: "商品準備中").page(params[:page]).per(5).order(created_at: :desc)
    elsif params[:sort] == "3"
      @orders = Order.where(status: "出荷済").page(params[:page]).per(5).order(created_at: :desc)
    else
      @orders = Order.page(params[:page]).per(5).order(created_at: :desc)
    end
      #総売上
  	  total = 0
      customer_total = 0
      @orders.each do |x|
        total += x.total_price
        @customer_total = x.total_price
      end
      @total = total
  end

  def update
      #@customer = Customer.find(params[:id])
      order = Order.find(params[:id])
      order.update(order_params)
      redirect_to admin_orders_path
  end

  private
  def order_params
  	  params.require(:order).permit(:customer_id,:status,:payment,:order_time, :total_price,:delivery_charge,:delivery_name,:postal_code, :destination)
  end
end

app/controllers/customers/carts_controller.rb
class Customers::CartsController < ApplicationController


  def create
      cart = current_customer.carts.new(cart_params)
      if Cart.where(item_id: cart.item_id).exists?
        cart_up = Cart.find_by(item_id: cart.item_id)
        cart_up.quantity += cart.quantity
        cart_up.update(quantity: cart_up.quantity)
        redirect_to customers_path(current_customer.id)
      else
        cart.customer_id = current_customer.id
        cart.save!
        redirect_to customers_path(current_customer.id)
      end
  end

  def show
      @item = Item.all
  end

  def update
    cart = Cart.find(params[:id])
    cart.update(cart_params)
    redirect_to customers_path(current_customer.id)
  end

  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    redirect_to customers_path(current_customer.id)
  end

  private
  def cart_params
      params.require(:cart).permit(:customer_id,:item_id,:quantity)
  end



end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  def edit
  	@customer = Customer.find(params[:id])
    @customers =Customer.page(params[:page]).per(1)
    @orders = Order.where(customer_id: @customer.id)
    @address= Address.where(customer_id: @customer.id)
    if @address.count == 0
      2.times { @customer.addresses.build }
    elsif @address.count == 1
      @customer.addresses.build
    else
    end
      total = 0
      customer_total = 0
      @orders.each do |x|
        total += x.total_price
        @customer_total = x.total_price
      end
      @total = total
  end


  def favorites
    @favorites = Favorite.where(customer_id: current_customer.id)
    @artists = Artist.all
    @labels = Label.all
    @categories = Category.all
  end

  def carts
    @customer = Customer.find_by(id: params[:id])
    @carts = Cart.where(customer_id: @customer.id)
  end

  def hide
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to edit_customers_customer_path(@customer)
  end

private
  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:phone_number,:email, addresses_attributes:[:id,:postal_code,:address,:_destroy])
  end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
	 before_action :item_params
  def create
    @favorite = Favorite.create(customer_id: current_customer.id, item_id: @item.id)
  end

  def destroy
    @favorite = Favorite.find_by(customer_id: current_customer.id, item_id: @item.id).destroy
  end

  private

  def item_params
    @item = Item.find(params[:item_id])
  end

end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def about
  end

  def thanks
  end

  def unsubscribe
  end

  def top
  	if customer_signed_in?
    @room = Room.new
    @rooms = current_customer.rooms
    @nonrooms = Room.where(id: CustomerRoom.where.not(customer_id: current_customer.id).pluck(:id))
  end
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def index
  	@items = Item.all.order(created_at: :desc).limit(4)
  	@arrival_items = ArrivalItem.all
    @artists = Artist.all
    @labels = Label.all
    @categories = Category.all
    @all_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(16).pluck(:item_id))
    @random = Item.order("RANDOM()").limit(8)
    @item_sale = Item.where(sale: 2).order(created_at: :desc).limit(5)
  end

  def index2
    @items = Item.page(params[:page]).per(16)
    @categories = Category.all
  end

  def show
  	@item = Item.find(params[:id])
    @cart = Cart.new
    @post_comment = PostComment.new
  end

  def category
    @category = Category.find(params[:id])
    @items = Item.where(category_id: @category.id)
    @categories = Category.all
  end

  def search
    @item_or_artist = params[:option]
    if @item_or_artist == "1"
      @items = Item.search(params[:search], @item_or_artist)
      @artists = Artist.all
      @labels = Label.all
      @categories = Category.all
    else
      @artist = Artist.search(params[:search], @item_or_artist)
      @items = Item.all
      @labels = Label.all
      @categories = Category.all
    end
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController


  def new
  	  @order = Order.new
  	  @customer = current_customer
      @carts = Cart.where(customer_id: @customer.id)
      @addresses = Address.where(customer_id: @customer.id)
      #@address = current_customer.address.find([])
  end

  def new_address
      @order = Order.new
  	  @customer = current_customer
      @carts = Cart.where(customer_id: @customer.id)
      @addresses = Address.where(customer_id: @customer.id)
  end

  def create
  	 #注文テーブル保存
  	  order = Order.new(order_params)
      order.total_price = params[:total_price]
      if order.save
        #注文詳細テーブル保存
        current_customer.carts.each do |n|
          order_detail = OrderDetail.new
           	order_detail.quantity = n.quantity
           	order_detail.item_id = n.item_id
          order_detail.tax = (order.total_price * 0.1).to_i
          order_detail.order_id = order.id
          order_detail.save!
          #在庫計算
          order_detail.item.stock -= order_detail.quantity
          order_detail.item.update(stock: order_detail.item.stock)
  	     end
        #カート削除
        current_customer.carts.where(customer_id:current_customer.id).destroy_all
        redirect_to customers_homes_thanks_path
      else
        @order = Order.new
        @customer = current_customer
        @carts = Cart.where(customer_id: @customer.id)
        @addresses = Address.where(customer_id: @customer.id)
        render :new
      end
  end

  def pay
      Payjp.api_key = "sk_test_c3fabecb879eaa80c4f3bb15"
      charge = Payjp::Charge.create(
      :amount => params[:total_price],
      :card => params['payjp-token'],
      :currency => 'jpy',
      )
  end

  private
  def order_params
  	  params.require(:order).permit(:customer_id,:status,:payment,:order_time, :total_price,:delivery_charge,:delivery_name,:postal_code, :destination)
  end

  def address_params
  	  params.require(:addresses).permit(:id,:postal_code,:address)
  end


end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/post_comments_controller.rb
class Customers::PostCommentsController < ApplicationController

	def create
		item = Item.find(params[:item_id])
		comment = current_customer.post_comments.new(post_comment_params)
		comment.item_id = item.id
		comment.save
		redirect_to customers_item_path(item)
	end

	def destroy
		post_comment = PostComment.find_by(item_id: params[:item_id])
    	post_comment.destroy
		redirect_to admin_item_path(post_comment.item)
	end

	def edit
		@post_comment = PostComment.find(params[:id])
		@item = Item.find(params[:item_id])
	end

	def update
		@post_comment = PostComment.find(params[:id])
    	@item = @post_comment.item.id
    	@post_comment.customer_id = current_customer.id
    	if @post_comment.update(post_comment_params)
      		redirect_to admin_item_path(@item)
    	else
      		render :edit
    	end
    	flash[:success] = 'CD was successfully updated.'
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:customer_id, :item_id, :comment)
	end

end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana,:first_name_kana, :postal_code,:address,:phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/rooms_controller.rb
class Customers::RoomsController < ApplicationController
  def show
  	  @room = Room.find(params[:id])
  	  @posts = @room.posts
  end

  def create
	  @room = Room.new(room_params)
	  @room.save
	  current_customer.customer_rooms.create(room_id: @room.id)
	  redirect_to customers_room_path(@room)
  end

  private
  def room_params
  	  params.require(:room).permit(:name)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/customers/orders/_order_detail_fields.html.erb
<%= f.label :注文詳細 %><br>
<%= f.hidden_field :quantity, :value => cart.quantity , class:"form-control" %>
<%= f.hidden_field :tax, :value => cart.item.price * cart.quantity * 0.1 , class:"form-control" %>

app/views/customers/orders/new.html.erb
<div class="order-content">
  <section class="container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2 order-container">
        <% if @order.errors.any? %>
          <%= @order.errors.count %>件のエラー。
          <% @order.errors.full_messages.each do |message| %>
            <%= message %>。
          <% end %>
        <% end %>
      <h2 class="text-center">購入確認</h2>
      <hr>
        <%= form_for(@order,url: customers_orders_path , method: :post) do |f| %>
            <h4 class="order-title">お届け先</h4>
            <%= f.label :宛名 %>
              <%= f.text_field :delivery_name, class:"form-control" %>
            <%= f.label :メイン住所 %>
            <div style="padding: 10px; margin-bottom: 10px; border: 1px solid #333333; width: 60%;">
                <%= f.radio_button :destination, @customer.address, checked:"checked" %>
                 <p>〒<%= @customer.postal_code %></p>
                 <p><%= @customer.address %></p>
                <%= f.hidden_field :postal_code, :value => @customer.postal_code, class:"form-control" %>
                <%= f.hidden_field :status, :value => :受付, class:"form-control" %>
                <%= f.hidden_field :order_time, :value => Time.now, class:"form-control" %>
                <%= f.hidden_field :delivery_charge, :value => 500, class:"form-control" %>
                <%= f.hidden_field :customer_id, :value => current_customer.id, class:"form-control" %>
            </div>
            <% if current_customer.addresses.where(customer_id: current_customer.id).exists? %>
              <%= f.label :その他登録住所 %>
              <div style= "padding: 10px; margin-bottom: 10px; border: 1px solid #333333; width: 60%;">
                <% @addresses.each.with_index(1) do |address,i| %>
                  <p>住所<%= i %></p>
                  <div style= "padding: 10px; margin-bottom: 10px; border: 1px solid #333333; width: 100%;">
                      <%= f.radio_button :destination, address.address %>
                      <p>〒<%= address.postal_code %></p>
                      <p><%= address.address %></p>
                      <%= f.hidden_field :postal_code, :value => address.postal_code, class:"form-control" %>
                      <%= f.hidden_field :status, :value => :受付, class:"form-control" %>
                      <%= f.hidden_field :order_time, :value => Time.now, class:"form-control" %>
                      <%= f.hidden_field :delivery_charge, :value => 500, class:"form-control" %>
                      <%= f.hidden_field :customer_id, :value => current_customer.id, class:"form-control" %>
                  </div>
                <% end %>
              </div>
            <% end %>
      <%= link_to "新しい送り先に送る場合は、こちら",customers_orders_new2_path %>

            <h4 class="order-title">注文内容</h4>
            <table  class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th>#</th>
                  <th>製品名</th>
                  <th>数量</th>
                  <th>価格</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                 <% sum = 0 %>
                  <% quantity_sum = 0 %>
                    <% @carts.each do |cart| %>
                      <tr>
                        <td><%= attachment_image_tag cart.item, :image, class: "book-img float-left", size: "50x50" %></td>
                        <td><%= cart.item.name %></td>
                        <td><%= cart.quantity %></td>
                        <td>¥<%= (cart.item.price * 1.1).to_i %>  (税込)</td>
                        <td><%= link_to "削除", customers_customer_cart_path(current_customer.id,cart.id), method: :delete,class: "btn btn-sm btn-link" %></td>
                      </tr>
                      <% sum += (cart.item.price * cart.quantity) %>
                      <% quantity_sum += cart.quantity %>
                   <% end %>
              </tbody>
            </table>
            <hr>
            <h5 class="text-right">
              商品の小計（<%= quantity_sum %>点）： ¥ <%= (sum * 1.1).to_i %> (税込)
              <br>送料（全国一律）： ¥ 500</br>
              ご請求額：¥ <%= (sum * 1.1).to_i + 500 %> (税込)
            </h5>
            <h4 class="order-title">支払い方法</h4>
              <div class="field">
                <table>
                  <tbody>
                  <td style="margin-right: 10px;"><%= f.radio_button :payment, :クレジットカード, checked:"checked" %>
                  <%= f.label :クレジットカード %></td>
                    <td><%= form_tag(action: :pay, method: :post) do |x| %>
                    <%= hidden_field_tag :total_price, sum %>
                      <script type="text/javascript"
                        src="https://checkout.pay.jp"
                        class="payjp-button"
                        data-key="pk_test_6f6c6927b0286421699ee2b5">
                      </script></td>
                  <td><%= f.radio_button :payment, :銀行振込 %>
                  <%= f.label :銀行振込 %></td>
                  <td><%= f.radio_button :payment, :代引き %>
                  <%= f.label :代引き %></td>
                </tbody>
            </table><br>
            </div>
            <%= f.hidden_field :total_price, :value => sum, class:"form-control" %>
            <%= f.submit '注文を確定する' , class:"btn btn-warning btn-block" %>
        <% end %>
        <% end %>
      </div>
    </div>
</section>
</div>

app/views/customers/orders/new_address.html.erb
<div class="order-content">
  <section class="container">
    <div class="row">
      <div class="col-md-8 col-sm-offset-2 order-container">
        <h2 class="text-center">購入確認</h2><%= link_to "戻る", new_customers_orders_path %>
        <hr>
          <%= form_for(@order,url: customers_orders_path , method: :post) do |f| %>
            <h4>新規お届け先</h4>
              <%= f.label :宛名 %>
                <%= f.text_field :delivery_name, class:"form-control" %>
              <%= f.label :郵便番号 %>
                <%= f.text_field :postal_code, class:"form-control" %>
              <%= f.label :住所 %>
                <%= f.text_area :destination, class:"form-control" %>
              <%= f.hidden_field :status, :value => :受付, class:"form-control" %>
              <%= f.hidden_field :order_time, :value => Time.now, class:"form-control" %>
              <%= f.hidden_field :delivery_charge, :value => 500, class:"form-control" %>
    　　　     <%= f.hidden_field :customer_id, :value => current_customer.id, class:"form-control" %>
             <h4 class="order-title">注文内容</h4>
            <table  class="table table-hover table-inverse">
              <thead>
                <tr>
                  <th>#</th>
                  <th>製品名</th>
                  <th>数量</th>
                  <th>価格</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                 <% sum = 0 %>
                  <% quantity_sum = 0 %>
                    <% @carts.each do |cart| %>
                      <tr>
                        <td><%= attachment_image_tag cart.item, :image, class: "book-img float-left", size: "50x50" %></td>
                        <td><%= cart.item.name %></td>
                        <td><%= cart.quantity %></td>
                        <td>¥<%= (cart.item.price * 1.1).to_i %>  (税込)</td>
                        <td><%= link_to "削除", customers_customer_cart_path(current_customer.id,cart.id), method: :delete,class: "btn btn-sm btn-link" %></td>
                      </tr>
                      <% sum += (cart.item.price * cart.quantity) %>
                      <% quantity_sum += cart.quantity %>
                   <% end %>
              </tbody>
            </table>
            <hr>
            <h5 class="text-right">
              商品の小計（<%= quantity_sum %>点）： ¥ <%= (sum * 1.1).to_i %> (税込)
              <br>送料（全国一律）： ¥ 500</br>
              ご請求額：¥ <%= (sum * 1.1).to_i + 500 %> (税込)
            </h5>
            <h4 class="order-title">支払い方法</h4>
              <div class="field">
                <table>
                  <tbody>
                  <td style="margin-right: 10px;"><%= f.radio_button :payment, :クレジットカード, checked:"checked" %>
                  <%= f.label :クレジットカード %></td>
                    <td><%= form_tag(action: :pay, method: :post) do |x| %>
                    <%= hidden_field_tag :total_price, sum %>
                      <script type="text/javascript"
                        src="https://checkout.pay.jp"
                        class="payjp-button"
                        data-key="pk_test_6f6c6927b0286421699ee2b5">
                      </script></td>
                  <td><%= f.radio_button :payment, :銀行振込 %>
                  <%= f.label :銀行振込 %></td>
                  <td><%= f.radio_button :payment, :代引き %>
                  <%= f.label :代引き %></td>
                </tbody>
            </table><br>
            </div>
            <%= f.hidden_field :total_price, :value => sum, class:"form-control" %>
            <%= f.submit '注文を確定する' , class:"btn btn-warning btn-block" %>
        <% end %>
        <% end %>
      </div>
    </div>
</section>
</div>