config/routes.rb
Rails.application.routes.draw do

  get  'index' =>'contact_mailers#index'
  post 'confirm' => 'contact_mailers#confirm'
  post 'done' => 'contact_mailers#done'
  resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy]

  namespace :customer do
    get 'customers/edit'
    get 'customers/favorites'
  end

  root 'customers/items#index'
  devise_for :admins, path: 'auth', path_names: { sign_in: 'panda_and_coffee_with_ryoko_play_login', sign_out: 'panda_and_coffee_with_ryoko_play_logout', password: 'panda_and_coffee_with_ryoko_play_secret', confirmation: 'panda_and_coffee_with_ryoko_play_verification', unlock: 'panda_and_coffee_with_ryoko_play_unblock', registration: 'panda_and_coffee_with_ryoko_play_register', sign_up: 'panda_and_coffee_with_ryoko_play_cmon_let_me_in' }, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations',
  }

  namespace :admin do
    resources :categories, only: [:create, :update]
    put 'categories/:id/hide' => 'categories#hide', as: 'categories_hide'
    resources :labels, only: [:create, :update]
    put 'labels/:id/hide' => 'labels#hide', as: 'labels_hide'
    resources :artists, only: [:create, :update]
    put 'artists/:id/hide' => 'artists#hide', as: 'artists_hide'

    get 'homes/index' => 'homes#index'
    get "search" => "arrival_items#search"
    get "history_search" => "arrival_items#history_search"
    get "fav" => "items#fav"

   put "/items/:id" => "items#hide"
   resources :items, only: [:new, :create, :edit, :update, :index, :show]
   resources :arrival_items, only: [:index, :new, :create, :update]


    put "/customers/:id" => "customers#hide"
    resources :customers, only: [:index, :show, :update, :edit]
    resources :orders, only: [:index, :update]

  end

  namespace :customers do
    get 'homes/about' => "homes#about"
    get 'homes/thanks' => "homes#thanks"
    get 'homes/top' => "homes#top"
    get ':id/unsubscribe' => "homes#unsubscribe", as: "unsubscribe"
    get "customers/:id/carts" => "customers#carts"
    get "search" => "items#search"
    get "category/:id" => "items#category"
    get "orders/new2" => "orders#new_address"
    resources :rooms, only: [:show, :create]

    resource :orders, only: [:new, :create] do
      post :pay, on: :member
    end

    resources :customers, only: [:edit] do
      resources :carts, only: [:show, :create, :update, :destroy]
    end

    resources :customers, only: [:edit,:update]
    put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
    get "/customers/:id" => "customers#favorites", as: 'favorites'
    get "/items/index2" => "items#index2"

    resources :items, only: [:show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :carts, only: [:show, :create, :update, :destroy]
      resources :post_comments, only: [:create, :destroy, :edit, :update]
    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord

	belongs_to :customer

	has_many :order_details, dependent: :destroy
    accepts_nested_attributes_for :order_details, allow_destroy: true
	validates :delivery_name, presence: true
	validates :postal_code, format: { with: /\A\d{3}[-]\d{4}\z/ }
	validates :destination, presence: true
    validates :payment, presence: true

    enum payment:{
    クレジットカード: 0,
    銀行振込: 1,
    代引き: 2
  }

    enum status:{
    受付: 0,
    商品準備中: 1,
    出荷済み: 2
    }


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    if params[:sort] == "1"
      @orders = Order.where(status: "受付").page(params[:page]).per(5).order(created_at: :desc)
    elsif params[:sort] == "2"
      @orders = Order.where(status: "商品準備中").page(params[:page]).per(5).order(created_at: :desc)
    elsif params[:sort] == "3"
      @orders = Order.where(status: "出荷済").page(params[:page]).per(5).order(created_at: :desc)
    else
      @orders = Order.page(params[:page]).per(5).order(created_at: :desc)
    end
      #総売上
  	  total = 0
      customer_total = 0
      @orders.each do |x|
        total += x.total_price
        @customer_total = x.total_price
      end
      @total = total
  end

  def update
      #@customer = Customer.find(params[:id])
      order = Order.find(params[:id])
      order.update(order_params)
      redirect_to admin_orders_path
  end

  private
  def order_params
  	  params.require(:order).permit(:customer_id,:status,:payment,:order_time, :total_price,:delivery_charge,:delivery_name,:postal_code, :destination)
  end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController


  def new
  	  @order = Order.new
  	  @customer = current_customer
      @carts = Cart.where(customer_id: @customer.id)
      @addresses = Address.where(customer_id: @customer.id)
      #@address = current_customer.address.find([])
  end

  def new_address
      @order = Order.new
  	  @customer = current_customer
      @carts = Cart.where(customer_id: @customer.id)
      @addresses = Address.where(customer_id: @customer.id)
  end

  def create
  	 #注文テーブル保存
  	  order = Order.new(order_params)
      order.total_price = params[:total_price]
      if order.save
        #注文詳細テーブル保存
        current_customer.carts.each do |n|
          order_detail = OrderDetail.new
           	order_detail.quantity = n.quantity
           	order_detail.item_id = n.item_id
          order_detail.tax = (order.total_price * 0.1).to_i
          order_detail.order_id = order.id
          order_detail.save!
          #在庫計算
          order_detail.item.stock -= order_detail.quantity
          order_detail.item.update(stock: order_detail.item.stock)
  	     end
        #カート削除
        current_customer.carts.where(customer_id:current_customer.id).destroy_all
        redirect_to customers_homes_thanks_path
      else
        @order = Order.new
        @customer = current_customer
        @carts = Cart.where(customer_id: @customer.id)
        @addresses = Address.where(customer_id: @customer.id)
        render :new
      end
  end

  def pay
      Payjp.api_key = "sk_test_c3fabecb879eaa80c4f3bb15"
      charge = Payjp::Charge.create(
      :amount => params[:total_price],
      :card => params['payjp-token'],
      :currency => 'jpy',
      )
  end

  private
  def order_params
  	  params.require(:order).permit(:customer_id,:status,:payment,:order_time, :total_price,:delivery_charge,:delivery_name,:postal_code, :destination)
  end

  def address_params
  	  params.require(:addresses).permit(:id,:postal_code,:address)
  end


end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/customer/orders_helper.rb
module Customer::OrdersHelper
end

app/views/admin/orders/index.html.erb
<section class="container-fluid clearfix">
  <h2 class="text-center">受注一覧</h2>
    <div class="row">
      <div class="col-md-8 col-sm-offset-2 order-container">
        <h5 class="text-left">絞り込む⇨
          <%= link_to "受付", admin_orders_path(sort: 1) %>/
          <%= link_to "商品準備中", admin_orders_path(sort: 2) %>/
          <%= link_to "出荷済", admin_orders_path(sort: 3) %>/
          <%= link_to "全て", admin_orders_path %>
        </h5>
        <h4 class="text-right">総売上¥<%= @total %></h4>
        <% @orders.each do |order| %>
              <div class="row order-container_box">
                  <div class="col-md-3">
                    <h7>購入者：<%= order.customer.last_name %><%= order.customer.first_name %></h7>
                  </div>
                  <div class="col-md-3">
                    <h7>受注日：<%= order.order_time.strftime("%Y年%m月%d日 ") %></h7>
                  </div>
                  <div class="col-md-3">
                    <%= form_for([:admins,order],url: admin_order_path(order.id) , method: :patch) do |f| %>
                      <%= f.select :status, [["受付", :受付],["商品準備中",:商品準備中],["出荷済み",:出荷済み]] %>
                      <%= f.submit "変更", class:"btn bg-info" %>
                    <% end %>
                </div>
                <div class="col-md-3">
                  売上金額¥<%= order.total_price %>
                </div>


                <div class="col-md-12">
                  <table  class="table table-hover table-inverse">
                    <thead>
                      <tr>
                        <th>ジャケット</th>
                        <th>製品名</th>
                        <th>受注枚数</th>
                        <th>単価</th>
                        <th>小計</th>
                      </tr>
                    </thead>
                    <hr>
                    <% sum = 0 %>
                      <tbody>
                        <% order.order_details.each do |order_detail| %>
                        <tr>
                          <td><%= attachment_image_tag order_detail.item, :image, class: "center-block", size: "50x50" %></td>
                          <td><%= order_detail.item.name %></td>
                          <td><%= order_detail.quantity %></td>
                          <td>¥<%= order_detail.item.price %></td>
                           <% sum = ( order_detail.quantity * order_detail.item.price ) %>
                          <td>¥<%= sum %></td>
                        </tr>
                        <% end %>
                      </tbody>
                  </table>
                </div>
              </div>
      <% end %>
      <%= paginate @orders, class: "pagenate" %>
    </div>
  </div>
</section>