config/routes.rb
Rails.application.routes.draw do

  get  'index' =>'contact_mailers#index'
  post 'confirm' => 'contact_mailers#confirm'
  post 'done' => 'contact_mailers#done'
  resources :contacts, only: [:index, :new, :create, :edit, :update, :destroy]

  namespace :customer do
    get 'customers/edit'
    get 'customers/favorites'
  end

  root 'customers/items#index'
  devise_for :admins, path: 'auth', path_names: { sign_in: 'panda_and_coffee_with_ryoko_play_login', sign_out: 'panda_and_coffee_with_ryoko_play_logout', password: 'panda_and_coffee_with_ryoko_play_secret', confirmation: 'panda_and_coffee_with_ryoko_play_verification', unlock: 'panda_and_coffee_with_ryoko_play_unblock', registration: 'panda_and_coffee_with_ryoko_play_register', sign_up: 'panda_and_coffee_with_ryoko_play_cmon_let_me_in' }, controllers: {
    sessions: 'admin/sessions',
    passwords: 'admin/passwords',
    registrations: 'admin/registrations',
  }

  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations',
  }

  namespace :admin do
    resources :categories, only: [:create, :update]
    put 'categories/:id/hide' => 'categories#hide', as: 'categories_hide'
    resources :labels, only: [:create, :update]
    put 'labels/:id/hide' => 'labels#hide', as: 'labels_hide'
    resources :artists, only: [:create, :update]
    put 'artists/:id/hide' => 'artists#hide', as: 'artists_hide'

    get 'homes/index' => 'homes#index'
    get "search" => "arrival_items#search"
    get "history_search" => "arrival_items#history_search"
    get "fav" => "items#fav"

   put "/items/:id" => "items#hide"
   resources :items, only: [:new, :create, :edit, :update, :index, :show]
   resources :arrival_items, only: [:index, :new, :create, :update]


    put "/customers/:id" => "customers#hide"
    resources :customers, only: [:index, :show, :update, :edit]
    resources :orders, only: [:index, :update]

  end

  namespace :customers do
    get 'homes/about' => "homes#about"
    get 'homes/thanks' => "homes#thanks"
    get 'homes/top' => "homes#top"
    get ':id/unsubscribe' => "homes#unsubscribe", as: "unsubscribe"
    get "customers/:id/carts" => "customers#carts"
    get "search" => "items#search"
    get "category/:id" => "items#category"
    get "orders/new2" => "orders#new_address"
    resources :rooms, only: [:show, :create]

    resource :orders, only: [:new, :create] do
      post :pay, on: :member
    end

    resources :customers, only: [:edit] do
      resources :carts, only: [:show, :create, :update, :destroy]
    end

    resources :customers, only: [:edit,:update]
    put "/customers/:id/hide" => "customers#hide", as: 'customers_hide'
    get "/customers/:id" => "customers#favorites", as: 'favorites'
    get "/items/index2" => "items#index2"

    resources :items, only: [:show, :index] do
      resource :favorites, only: [:create, :destroy]
      resources :carts, only: [:show, :create, :update, :destroy]
      resources :post_comments, only: [:create, :destroy, :edit, :update]
    end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def show
  	@customer = Customer.find(params[:id])
  	@customers =Customer.page(params[:page]).per(2)
  	@orders = Order.where(customer_id: @customer.id)
  	 #総売上
  	  total = 0
      customer_total = 0
      @orders.each do |x|
        total += x.total_price
        @customer_total = x.total_price
      end
      @total = total
  end


  def hide
  	@customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
  	redirect_to root_path
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def index
    @customer =Customer.page(params[:page]).per(1)
     @orders = Order.all
     if params[:vort] == "2"
      @customers = Customer.all
    else
      @customers = Customer.all.order(created_at: :desc)
  end
end

  def update
  	@customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end
private
def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:phone_number,:email, addresses_attributes:[:id,:postal_code,:address,:is_deleted])
end
def correct_user
    user = Customer.find(params[:id])
    if current_user != customer
      redirect_to admin_customers_path(current_user)
    end
   end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
    @item.arrival_items.build
    @item.disks.build
     @item.disks.each do |disks|
      disks.songs.build
     end
    @arrival_item = ArrivalItem.new
    @artists = Artist.where(is_deleted: false)
    @labels = Label.where(is_deleted: false)
    @categories = Category.where(is_deleted: false)
  end

  def create
    @item = Item.new(item_params)
    @arrival_item = ArrivalItem.new
    if @item.save
       @arrival_item.arrival_count = @item.stock
       @arrival_item.item_id = @item.id
       @arrival_item.arrival_time = @item.release_date
       @arrival_item.save!
      redirect_to admin_items_path
    else
      @artists = Artist.all
      @labels = Label.all
      @categories = Category.all
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
        redirect_to admin_items_path
    else
        render :edit
    end
    flash[:success] = 'Wear was successfully updated.'
  end

  def hide
    @item = Item.find(params[:id])
    @item.update(is_deleted: true)
    redirect_to root_path
  end

  def index
    @items = Item.all.order(created_at: :desc).limit(4)
    @arrival_items = ArrivalItem.all
    @artists = Artist.all
    @labels = Label.all
    @categories = Category.all
    @all_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(4).pluck(:item_id))
    @random = Item.order("RANDOM()").limit(8)
  end

  def fav
    @arrival_items = ArrivalItem.all
    @artists = Artist.all
    @labels = Label.all
    @categories = Category.all
    @all_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(16).pluck(:item_id))
    @random = Item.order("RANDOM()").limit(8)
  end

  def show
    @item = Item.find(params[:id])
    @cart = Cart.new
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :release_date, :comment, :status, :sale, :image, :artist_id, :label_id, :category_id, :stock, arrival_items_attributes: [:id, :arrival_count, :arrival_time, :is_deleted], disks_attributes: [:id, :disk_order, :_destroy, songs_attributes: [:id, :name, :song_order, :_destroy]])
  end

end

app/controllers/customers/carts_controller.rb
class Customers::CartsController < ApplicationController


  def create
      cart = current_customer.carts.new(cart_params)
      if Cart.where(item_id: cart.item_id).exists?
        cart_up = Cart.find_by(item_id: cart.item_id)
        cart_up.quantity += cart.quantity
        cart_up.update(quantity: cart_up.quantity)
        redirect_to customers_path(current_customer.id)
      else
        cart.customer_id = current_customer.id
        cart.save!
        redirect_to customers_path(current_customer.id)
      end
  end

  def show
      @item = Item.all
  end

  def update
    cart = Cart.find(params[:id])
    cart.update(cart_params)
    redirect_to customers_path(current_customer.id)
  end

  def destroy
    cart = Cart.find(params[:id])
    cart.destroy
    redirect_to customers_path(current_customer.id)
  end

  private
  def cart_params
      params.require(:cart).permit(:customer_id,:item_id,:quantity)
  end



end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/customers_controller.rb
class Customers::CustomersController < ApplicationController
  def edit
  	@customer = Customer.find(params[:id])
    @customers =Customer.page(params[:page]).per(1)
    @orders = Order.where(customer_id: @customer.id)
    @address= Address.where(customer_id: @customer.id)
    if @address.count == 0
      2.times { @customer.addresses.build }
    elsif @address.count == 1
      @customer.addresses.build
    else
    end
      total = 0
      customer_total = 0
      @orders.each do |x|
        total += x.total_price
        @customer_total = x.total_price
      end
      @total = total
  end


  def favorites
    @favorites = Favorite.where(customer_id: current_customer.id)
    @artists = Artist.all
    @labels = Label.all
    @categories = Category.all
  end

  def carts
    @customer = Customer.find_by(id: params[:id])
    @carts = Cart.where(customer_id: @customer.id)
  end

  def hide
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to edit_customers_customer_path(@customer)
  end

private
  def customer_params
    params.require(:customer).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:postal_code,:address,:phone_number,:email, addresses_attributes:[:id,:postal_code,:address,:_destroy])
  end
end

app/controllers/customers/favorites_controller.rb
class Customers::FavoritesController < ApplicationController
	 before_action :item_params
  def create
    @favorite = Favorite.create(customer_id: current_customer.id, item_id: @item.id)
  end

  def destroy
    @favorite = Favorite.find_by(customer_id: current_customer.id, item_id: @item.id).destroy
  end

  private

  def item_params
    @item = Item.find(params[:item_id])
  end

end

app/controllers/customers/homes_controller.rb
class Customers::HomesController < ApplicationController
  def about
  end

  def thanks
  end

  def unsubscribe
  end

  def top
  	if customer_signed_in?
    @room = Room.new
    @rooms = current_customer.rooms
    @nonrooms = Room.where(id: CustomerRoom.where.not(customer_id: current_customer.id).pluck(:id))
  end
  end
end

app/controllers/customers/items_controller.rb
class Customers::ItemsController < ApplicationController
  def index
  	@items = Item.all.order(created_at: :desc).limit(4)
  	@arrival_items = ArrivalItem.all
    @artists = Artist.all
    @labels = Label.all
    @categories = Category.all
    @all_ranks = Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(16).pluck(:item_id))
    @random = Item.order("RANDOM()").limit(8)
    @item_sale = Item.where(sale: 2).order(created_at: :desc).limit(5)
  end

  def index2
    @items = Item.page(params[:page]).per(16)
    @categories = Category.all
  end

  def show
  	@item = Item.find(params[:id])
    @cart = Cart.new
    @post_comment = PostComment.new
  end

  def category
    @category = Category.find(params[:id])
    @items = Item.where(category_id: @category.id)
    @categories = Category.all
  end

  def search
    @item_or_artist = params[:option]
    if @item_or_artist == "1"
      @items = Item.search(params[:search], @item_or_artist)
      @artists = Artist.all
      @labels = Label.all
      @categories = Category.all
    else
      @artist = Artist.search(params[:search], @item_or_artist)
      @items = Item.all
      @labels = Label.all
      @categories = Category.all
    end
  end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/orders_controller.rb
class Customers::OrdersController < ApplicationController


  def new
  	  @order = Order.new
  	  @customer = current_customer
      @carts = Cart.where(customer_id: @customer.id)
      @addresses = Address.where(customer_id: @customer.id)
      #@address = current_customer.address.find([])
  end

  def new_address
      @order = Order.new
  	  @customer = current_customer
      @carts = Cart.where(customer_id: @customer.id)
      @addresses = Address.where(customer_id: @customer.id)
  end

  def create
  	 #注文テーブル保存
  	  order = Order.new(order_params)
      order.total_price = params[:total_price]
      if order.save
        #注文詳細テーブル保存
        current_customer.carts.each do |n|
          order_detail = OrderDetail.new
           	order_detail.quantity = n.quantity
           	order_detail.item_id = n.item_id
          order_detail.tax = (order.total_price * 0.1).to_i
          order_detail.order_id = order.id
          order_detail.save!
          #在庫計算
          order_detail.item.stock -= order_detail.quantity
          order_detail.item.update(stock: order_detail.item.stock)
  	     end
        #カート削除
        current_customer.carts.where(customer_id:current_customer.id).destroy_all
        redirect_to customers_homes_thanks_path
      else
        @order = Order.new
        @customer = current_customer
        @carts = Cart.where(customer_id: @customer.id)
        @addresses = Address.where(customer_id: @customer.id)
        render :new
      end
  end

  def pay
      Payjp.api_key = "sk_test_c3fabecb879eaa80c4f3bb15"
      charge = Payjp::Charge.create(
      :amount => params[:total_price],
      :card => params['payjp-token'],
      :currency => 'jpy',
      )
  end

  private
  def order_params
  	  params.require(:order).permit(:customer_id,:status,:payment,:order_time, :total_price,:delivery_charge,:delivery_name,:postal_code, :destination)
  end

  def address_params
  	  params.require(:addresses).permit(:id,:postal_code,:address)
  end


end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/post_comments_controller.rb
class Customers::PostCommentsController < ApplicationController

	def create
		item = Item.find(params[:item_id])
		comment = current_customer.post_comments.new(post_comment_params)
		comment.item_id = item.id
		comment.save
		redirect_to customers_item_path(item)
	end

	def destroy
		post_comment = PostComment.find_by(item_id: params[:item_id])
    	post_comment.destroy
		redirect_to admin_item_path(post_comment.item)
	end

	def edit
		@post_comment = PostComment.find(params[:id])
		@item = Item.find(params[:item_id])
	end

	def update
		@post_comment = PostComment.find(params[:id])
    	@item = @post_comment.item.id
    	@post_comment.customer_id = current_customer.id
    	if @post_comment.update(post_comment_params)
      		redirect_to admin_item_path(@item)
    	else
      		render :edit
    	end
    	flash[:success] = 'CD was successfully updated.'
	end

	private
	def post_comment_params
		params.require(:post_comment).permit(:customer_id, :item_id, :comment)
	end

end

app/controllers/customers/rooms_controller.rb
class Customers::RoomsController < ApplicationController
  def show
  	  @room = Room.find(params[:id])
  	  @posts = @room.posts
  end

  def create
	  @room = Room.new(room_params)
	  @room.save
	  current_customer.customer_rooms.create(room_id: @room.id)
	  redirect_to customers_room_path(@room)
  end

  private
  def room_params
  	  params.require(:room).permit(:name)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/customers/items/_favorite.html.erb
<% if customer_signed_in? %>
	<% if item.favorited_by?(current_customer) %>
		<%= link_to customers_item_favorites_path(item), method: :delete, remote: true do %>
			<i class="fa fa-heart" aria-hidden="true" style="color: red;">
				<%= item.favorites.count %>
			</i>
		<% end %>
	<% else %>
		<%= link_to customers_item_favorites_path(item), method: :post, remote: true do %>
			<i class="fa fa-heart" aria-hidden="true">
				<%= item.favorites.count %>
			</i>
		<% end %>
	<% end %>
<% else %>
	<i class="fa fa-heart" aria-hidden="true">
			<%= item.favorites.count %>
	</i>
<% end %>

app/views/customers/items/_search.html.erb
<div class="search-btn">
	<i class="fas fa-search", style= "margin-left: 5px; margin-top: 28px;"></i>
		<div class="search-form">
			<%= form_tag(customers_search_path, :method => 'get') do %>
			    <%= select_tag(:option, options_for_select([["アルバム名", "1"],["アーティスト","2"]]))%>
			    <%= text_field_tag :search, params[:search], class: "form-control" %>
			    <%= submit_tag '検索', class: "btn btn-info" %>
			<% end %>
		</div>
</div>

app/views/customers/items/_show_favorite.html.erb
<% if customer_signed_in? %>
	<% if item.favorited_by?(current_customer) %>
		<%= link_to customers_item_favorites_path(item), method: :delete, remote: true do %>
			<i class="fa fa-heart btn btn-lg btn-block btn-base-1 mt-20 bg-info" aria-hidden="true">
				<span>いいねを外す</span>
			</i>
		<% end %>
		<% else %>
		<%= link_to customers_item_favorites_path(item), method: :post, remote: true do %>
			<i class="fa fa-heart btn btn-lg btn-block btn-base-1 mt-20 bg-info" aria-hidden="true">
			    <span>いいねする</span>
			</i>
		<% end %>
	<% end %>
<% else %>
	<%= link_to new_customer_session_path do %>
		<i class="fa fa-heart btn btn-lg btn-block btn-base-1 mt-20 bg-info" aria-hidden="true">
				<span>いいねする</span>
		</i>
	<% end %>
<% end %>

app/views/customers/items/search.html.erb
<% if @item_or_artist == "1"%>
    <%= render 'item' %>

<% elsif @item_or_artist == "2" %>
    <%= render 'artist' %>

<% else %>
<% end %>

app/views/customers/items/show.html.erb
<div class="show-content">
<section class="container-fluid clearfix">
	<h1 class="text-center">商品詳細</h1>
		<div class="row">
			<div class="col-md-8 col-sm-offset-2 show-container">
				<div class="row clearfix">
					<div class="col-md-6">
						<div class="item_show">
							<div class="item_show_image">
								<%= attachment_image_tag @item, :image, size: "300x300", class: "center-block" %>
							</div>
						</div>
					</div>

					<div class="col-md-6">
						<table class="table table-striped">
							<thead>
								<tr>
									<th>シングルアルバム名</th>
									<th><%= @item.name %></th>
								</tr>
								<tr>
									<th>アーティスト名</th>
									<th><%= @item.artist.name %></th>
								</tr>
								<tr>
									<th>価格(税込)</th>
									<th>¥ <%= (@item.price * 1.1).to_i %>
										<% if @item.sale == "好評発売中" %>
				  							<span class="btn btn-info btn-xs">好評発売中</span>
				  						<% elsif @item.sale == "販売停止中" %>
				  							<span class="btn btn-warning btn-xs">販売停止中</span>
				  						<% else %>
				  							<span class="btn btn-danger btn-xs">sale</span>
				  						<% end %>
									</th>
								</tr>
								<tr>
									<th>発売日</th>
									<th><%= @item.release_date.strftime("%Y年%m月%d日 ") %></th>
								</tr>
								<tr>
									<th>レーベル名</th>
									<th><%= @item.label.name %></th>
								</tr>
								<tr>
									<th>カテゴリー名</th>
									<th><%= @item.category.name %></th>
								</tr>
								<tr>
									<th>在庫</th>
									<th><% if @item.stock == 0 %>
				  							<p class="btn btn-danger btn-xs">在庫なし</p>
				  						<% elsif @item.stock <= 5 %>
				  							<p class="btn btn-warning btn-xs">残り在庫<%= @item.stock %>ケ</p>
				  						<% else %>
				  							<p class="btn btn-success btn-xs">在庫あり</p>
				  						<% end %>
				  					</th>
								</tr>
							</thead>
						</table>
					</div>
		        </div>
		        <hr>


					<div class="row">
						<h3 class="text-left">
  							<span class="show-title">店長の一言</span>
  						</h3>
						<div class="comment">
							<%= @item.comment %></p>
						</div>
						<hr>
						<h3 class="text-left">
  							<span class="show-title">製品内容</span>
  						</h3>
						<div class ="disk">
							<% @item.disks.each do |disk| %>
								<p>ディスク<%= disk.disk_order %><br>
									<% disk.songs.each do |song| %>
										<p><%= song.song_order %>.<%= song.name %></p>
									<% end %>
								</p>
							<% end %>
						</div>
					</div>
						<hr>

					<div class="row">
					  <ul>
						<li class="comment-create">
		  					<h3 class="text-left comment-title">レビュー<i class="fas fa-folder-open"></i></h3>
		  					<% if @post_comment.errors.any? %>
					          <%= @post_comment.errors.count %>件のエラー。
					          <% @post_comment.errors.full_messages.each do |message| %>
					            <%= message %>。
					          <% end %>
					        <% end %>
			  				<div class="comment">
				  				<h4 class="comment-count">
		  							<%= @item.post_comments.count %>件レビュー
		  						</h4>
	  							<% @item.post_comments.each do |post_comment| %>
	  									<div class="comment-entry">
	  										<b><%= post_comment.customer.last_name %>さん</b><br>
	  				    					<%= post_comment.comment %>
	  				    				</div>
	  				    		<% end %>
	  				    	</div>
	  				    </li>
	  				</ul>
	  				<% if customer_signed_in? %>
  						<%= form_for([@item, @post_comment], url: customers_item_post_comments_path(@item), method: :post) do |f| %>
	  						<div class="col-md-12 comment-submit">
	  							<%= f.text_field :comment, class: "form-control",placeholder: "レビューをここに" %>
	  						</div>
	  						<%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
  						<% end %>
			  		<% end %>
  					</div>
  					<hr>

					<div class="row">
						<div class="col-md-8 col-md-offset-2">
							<div id="item__show_favorite_<%= @item.id %>">
					             <%= render 'show_favorite', item: @item %>
							</div>
						</div>
					</div>
						<hr>

					<% if customer_signed_in? %>
						<%if @item.sale == "販売停止中" %>
							<div class="col-md-8 col-md-offset-2">
								<h2 class="btn btn-lg btn-block btn-base-1 mt-20 bg-danger">
									販売停止中です
								</h2>
							</div>
						<% else %>
							<%= form_for(@cart, url: customers_customer_carts_path(current_customer.id), method: :post) do |f| %>
								<div class="row clearfix">
									<div class="col-md-7 col-md-offset-2">
										<%= f.submit "カートへ入れる", class:"btn btn-lg btn-block btn-base-1 mt-20 bg-success" %>
									</div>
									<div class="col-md-1">
										<%= f.select :quantity, options_for_select((1..@item.stock).to_a, @cart.quantity) %>
										<%= f.hidden_field :item_id, :value => @item.id, class:"form-control" %>
									</div>
							<% end %>
								</div>
						<% end %>
							<hr>
					<% else %>
						<%= link_to new_customer_session_path do %>
							<button type="button" class="btn btn-lg btn-block btn-base-1 mt-20 bg-success">カートへ入れる</button>
						<% end %>
					<% end %>


					<div class="row">
							<div class="col-md-10 col-md-offset-1">
								<div class="slide-block">
								<h2 class="slide-block_text">店長のおすすめ</h2>
								<div class="slider">
									<%= image_tag "jacketby(1)", size: "100x100" %>
									<%= image_tag "jacketby(2)", size: "100x100" %>
									<%= image_tag "jacketby(3)", size: "100x100" %>
									<%= image_tag "jacketby(4)", size: "100x100" %>
									<%= image_tag "jacketby(5)", size: "100x100" %>
									<%= image_tag "jacketby (6)", size: "100x100" %>
									<%= image_tag "jacketby(7)", size: "100x100" %>
									<%= image_tag "jacketby (8)", size: "100x100" %>
									<%= image_tag "jacketby (9)", size: "100x100" %>
									<%= image_tag "jacketby(10)", size: "100x100" %>
								</div>
							</div>
							</div>
					</div>

				</div>
			</div>
		</div>

		<span id="back">
		      <a href="">
		        <%= image_tag "arrow.png", size: "30x30", class: "pull-right" %>
		      </a>
		</span>
</section>
</div>